# Build Stage
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# We accept the build arguments for API keys
ARG VITE_API_BASE_URL
ARG GEMINI_API_KEY
ARG OPENAI_API_KEY
ARG EVOLUTION_API_URL
ARG EVOLUTION_API_KEY
ARG INSTANCE_NAME
ARG INSTANCE_NAME_2
ARG ACCESS_EMAIL
ARG ACCESS_PASSWORD

# Pass them to the build process
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV GEMINI_API_KEY=$GEMINI_API_KEY
ENV OPENAI_API_KEY=$OPENAI_API_KEY
ENV EVOLUTION_API_URL=$EVOLUTION_API_URL
ENV EVOLUTION_API_KEY=$EVOLUTION_API_KEY
ENV INSTANCE_NAME=$INSTANCE_NAME
ENV INSTANCE_NAME_2=$INSTANCE_NAME_2
ENV ACCESS_EMAIL=$ACCESS_EMAIL
ENV ACCESS_PASSWORD=$ACCESS_PASSWORD
RUN npm run build

# Production Stage
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
